---
- name: Clean up Single-Node OpenShift (SNO) cluster and release Equinix Machines with VMware vSphere
  hosts: localhost
  gather_facts: no

  vars:
    temp_directory: "{{ playbook_dir }}/tmp"

  tasks:

    - include_role:
        name: vsphere
        tasks_from: destroy

    - include_role:
        name: karmab.aicli.ai_cluster
      vars:
        name: "{{ cluster_name }}"
        state: absent
        offlinetoken: "{{ ocm_offline_token }}"
