---
- name: Clean up Single-Node OpenShift (SNO) cluster and release Equinix Machines with VMware vSphere
  hosts: localhost
  gather_facts: no

  vars:
    temp_directory: "{{ playbook_dir }}/tmp"

  roles:
    - karmab.ansible_aicli_modules

  tasks:

    - include_role:
        name: vsphere
        tasks_from: destroy

    - name: Delete the assisted SNO cluster
      ai_cluster:
        name: "{{ cluster_name }}"
        state: absent
        offlinetoken: "{{ ocm_offline_token }}"
