---
- name: Clean up Single-Node OpenShift (SNO) cluster and release Equinix Machines with VMware vSphere
  hosts: localhost
  gather_facts: no

  tasks:

    - include_role:
        name: vsphere
        tasks_from: destroy
      vars:
        temp_directory: "{{ local_temp_dir }}"

    - name: Delete the assisted cluster
      karmab.aicli.ai_cluster:
        name: "{{ openshift_cluster_name }}"
        state: absent
        offlinetoken: "{{ ocm_offline_token }}"
