---
roles:
  - name: karmab.ansible_aicli_modules

collections:
  - amazon.aws
  - community.general
  # TODO: Replace with just `community.vmware` once 2.5.0 has been released
  - name: https://github.com/empovit/community.vmware.git
    type: git
    version: 2.5.0-pre
