---
roles:
  - name: empovit.gpu_operator
    src: https://github.com/empovit/ansible-gpu-operator
    version: v1.0.0

collections:
  - amazon.aws
  - community.general
  - community.vmware
  - karmab.aicli
  - name: https://github.com/empovit/ansible-assisted-openshift.git
    type: git
    version: v1.0.0