---
roles:
  - name: karmab.ansible_aicli_modules
  - name: empovit.gpu_operator
    src: https://github.com/empovit/ansible-gpu-operator

collections:
  - amazon.aws
  - community.general
  - community.vmware