---
roles:
  - name: karmab.ansible_aicli_modules
  - name: empovit.gpu_operator
    src: https://github.com/empovit/ansible-gpu-operator

collections:
  - amazon.aws
  - community.general
  # TODO: Replace with just `community.vmware` once 2.5.0 has been released
  - name: https://github.com/empovit/community.vmware.git
    type: git
    version: 2.5.0-pre
