---
- name: S3 artifacts for vSphere deployment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Python prerequisites
      ansible.builtin.pip:
        name: ['boto3', 'botocore']
    - name: Bucket creation
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        s3_url: "{{ s3_url }}"
        mode: create
    - name: Deployment artifacts upload
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ item }}"
        src: "{{ s3_artifacts_dir }}/{{ item }}"
        s3_url: "{{ s3_url }}"
        mode: put
        overwrite: different
      with_items:
        - vsanapiutils.py
        - vsanmgmtObjects.py
        - NVD-VGPU_510.47.03-1OEM.702.0.0.17630552_19297162.zip
        - VMware-VCSA-all-7.0.3-19234570.iso
