# https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html
# https://docs.ansible.com/ansible/latest/collections/community/vmware/docsite/scenario_guide.html
# https://docs.ansible.com/ansible/latest/collections/community/vmware/docsite/vmware_scenarios/scenario_vmware_http.html
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html
---
- name: Single-Node OpenShift
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_username: "Administrator@vsphere.local"
    # Run `nvidia-smi vgpu -s | sort -u | grep -i grid | awk '{print "grid_"tolower($2)}'` on ESXi to see supported profiles
    # or `vim-cmd hostsvc/hostconfig` and scroll down to `sharedPassthruGpuTypes`
    vgpu_profile: "undefined" 
  tasks:
    - name: Python prerequisites
      ansible.builtin.pip:
        name: "PyVmomi"

    # - name: Host graphics for vGPU setup
    #   community.vmware.vmware_host_config_manager:
    #     hostname: "{{ vcenter_ip }}"
    #     username: "{{ vcenter_username }}"
    #     password: "{{ vcenter_password }}"
    #     esxi_hostname: "{{ esxi_hostname }}"
    #     # the list of advanced options can be found by running `vim-cmd hostsvc/advopt/options` on ESXi host
    #     options:
    #         'Config.Hardware.graphics.': false

    - name: SNO cluster
      ansible.builtin.shell: echo "SNO cluster"

    - name: ISO download
      ansible.builtin.shell: echo "ISO download"

    - name: VMware VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: /
        datacenter: Metal
        validate_certs: no
        name: sno_vm
        state: present
        guest_id: rhel8_64Guest
        disk:
        - size_gb: 180
          type: thin
          datastore: datastore1
        networks:
        - name: VM Public Net 1
          start_connected: yes
        cdrom:
          type: iso
          iso_path: "[datastore1] livecd.iso"
        hardware:
          memory_mb: 32768
          num_cpus: 8
          scsi: paravirtual
          boot_firmware: "efi"
        advanced_settings:
        - key: "pciPassthru.use64bitMMIO"
          value: "TRUE"
        - key: "pciPassthru.64bitMMIOSizeGB"
          value: "512"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy_vm

    - name: SNO installation
      ansible.builtin.shell: echo "SNO installation"

    - name: NFD operator installation
      ansible.builtin.shell: echo "NFD operator"

    - name: GPU operator installation
      ansible.builtin.shell: echo "GPU operator"
