---
- name: VMware vSphere deployment
  hosts: localhost
  tasks:
    - name: Current Terraform state
      community.general.terraform:
        project_path: "{{ playbook_dir }}/equinix"
        state_file: "{{ playbook_dir }}/equinix/terraform.tfstate"
        state: planned
        plan_file: "{{ playbook_dir }}/equinix/terraform.tfplan"
    - name: Download vGPU VIB
      command: "mc cp s3/{{ s3_bucket }}/{{ vgpu_vib_filename }} ."
      args:
        chdir: bootstrap
    - name: Copy script for installing vGPU VIB
      copy:
        src: install_vgpu_vib.py
        dest: bootstrap/install_vgpu_vib.py
        mode: u+x
