- name: Download vGPU VIB from S3 storage
  ansible.builtin.command: "mc cp s3/{{ s3_bucket }}/{{ vib_filename }} ."
  args:
    chdir: bootstrap

- name: Copy script for installing vGPU on all remote ESXi hosts
  ansible.builtin.template:
    src: templates/install_vgpu.py.j2
    dest: bootstrap/install_vgpu.py
    mode: u=xwr,g=r,o=r

- name: Copy script for locally installing VIB on an ESXi host
  ansible.builtin.template:
    src: templates/install_vib_esxi.sh.j2
    dest: bootstrap/install_vib_esxi.sh
    mode: u=xwr,g=r,o=r

- name: Install vGPU host driver on all ESXi hosts
  ansible.builtin.command: "python3 $HOME/bootstrap/install_vgpu.py"
  args:
    chdir: bootstrap

- name: Wait for vCenter to become available after reboot
  ansible.builtin.uri:
    url: "https://{{ vcenter_ip }}/ui/"
    method: GET
    validate_certs: no
  register: _result
  until: _result.status == 200
  retries: 10
  delay: 120