- name: Install Python dependencies
  ansible.builtin.pip:
    name:
      - PyVmomi>=7.0.3
    state: present

- name: Copy Host graphics script to the bastion
  ansible.builtin.copy:
    src: update_host_graphics.py
    dest: bootstrap/update_host_graphics.py
    mode: u=xwr,g=r,o=r

- name: Change Host graphics to Shared Direct
  ansible.builtin.command:
    argv:
      - "python3"
      - "$HOME/bootstrap/update_host_graphics.py"
      - "--host={{ vcenter_ip }}"
      - "--user={{ vcenter_username }}"
      - "--passwd={{ vcenter_password }}"
      - "--graphics=sharedDirect"
      - "--ignore-certs"
  args:
    chdir: bootstrap

  # Simply restarting Xorg might not work, and reboot may be required
- name: Restart X.Org Server service for host graphics to take effect
  community.vmware.vmware_host_service_manager:
    hostname: "{{ vcenter_ip }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: Metal-1
    state: restart
    service_name: xorg
    validate_certs: no
